/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import dao.DaoProducto;
import javax.swing.JOptionPane;
import modelos.Producto;

/**
 *
 * @author jhonj
 */
public class CrearProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearProductos
     */
    public CrearProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCebeceraProCrear = new javax.swing.JPanel();
        lblCrearProducto = new javax.swing.JLabel();
        panelCuerpoProCrear = new javax.swing.JPanel();
        lblNombreProducto = new javax.swing.JLabel();
        txtCajaNombrePro = new javax.swing.JTextField();
        lblRefeProducto = new javax.swing.JLabel();
        txtCajaReferencia = new javax.swing.JTextField();
        lblTemperatura = new javax.swing.JLabel();
        txtCajaTemperatura = new javax.swing.JTextField();
        lblValorBase = new javax.swing.JLabel();
        txtCajaValorBase = new javax.swing.JTextField();
        panelBotonesProCrear = new javax.swing.JPanel();
        btnCrearProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(698, 532));

        panelCebeceraProCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCrearProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCrearProducto.setText("CREAR PRODUCTO");

        javax.swing.GroupLayout panelCebeceraProCrearLayout = new javax.swing.GroupLayout(panelCebeceraProCrear);
        panelCebeceraProCrear.setLayout(panelCebeceraProCrearLayout);
        panelCebeceraProCrearLayout.setHorizontalGroup(
            panelCebeceraProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCebeceraProCrearLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(lblCrearProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCebeceraProCrearLayout.setVerticalGroup(
            panelCebeceraProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCebeceraProCrearLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCrearProducto)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panelCuerpoProCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreProducto.setText("NOMBRE: ");

        txtCajaNombrePro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblRefeProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRefeProducto.setText("REFERENCIA: ");

        txtCajaReferencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTemperatura.setText("TEMPERATURA: ");

        txtCajaTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCajaTemperatura.setText("0");

        lblValorBase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorBase.setText("VALOR BASE: ");

        txtCajaValorBase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCajaValorBase.setText("0");

        javax.swing.GroupLayout panelCuerpoProCrearLayout = new javax.swing.GroupLayout(panelCuerpoProCrear);
        panelCuerpoProCrear.setLayout(panelCuerpoProCrearLayout);
        panelCuerpoProCrearLayout.setHorizontalGroup(
            panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoProCrearLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCuerpoProCrearLayout.createSequentialGroup()
                        .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRefeProducto)
                            .addComponent(lblNombreProducto))
                        .addGap(38, 38, 38)
                        .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCajaReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCajaNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCuerpoProCrearLayout.createSequentialGroup()
                        .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTemperatura)
                            .addComponent(lblValorBase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCajaTemperatura)
                            .addComponent(txtCajaValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelCuerpoProCrearLayout.setVerticalGroup(
            panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoProCrearLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto)
                    .addComponent(txtCajaNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefeProducto)
                    .addComponent(txtCajaReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperatura)
                    .addComponent(txtCajaTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCajaValorBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorBase))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panelBotonesProCrear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrearProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCrearProducto.setText("CREAR");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        btnCancelarProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelarProducto.setText("CANCELAR");

        javax.swing.GroupLayout panelBotonesProCrearLayout = new javax.swing.GroupLayout(panelBotonesProCrear);
        panelBotonesProCrear.setLayout(panelBotonesProCrearLayout);
        panelBotonesProCrearLayout.setHorizontalGroup(
            panelBotonesProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesProCrearLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnCrearProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarProducto)
                .addGap(16, 16, 16))
        );
        panelBotonesProCrearLayout.setVerticalGroup(
            panelBotonesProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesProCrearLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelBotonesProCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearProducto)
                    .addComponent(btnCancelarProducto))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCebeceraProCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuerpoProCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotonesProCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCebeceraProCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCuerpoProCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotonesProCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtCajaNombrePro.setText("");
        txtCajaReferencia.setText("");
        txtCajaTemperatura.setText("");
        txtCajaValorBase.setText("");
        txtCajaNombrePro.requestFocus();
    }
    
    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        //*************************************************************
        //definicion de variables
        //*************************************************************
        String cajaNombre, cajaReferencia;
        Double cajaTemperatura, cajaValorBase;
        DaoProducto objDaoProducto;
        Producto objProducto;
        //*************************************************************
        //*************************************************************
        //capturar informacion 
        //*************************************************************
        cajaNombre = txtCajaNombrePro.getText();
        cajaReferencia = txtCajaReferencia.getText();
        cajaTemperatura = Double.parseDouble(txtCajaTemperatura.getText());
        cajaValorBase = Double.parseDouble(txtCajaValorBase.getText());
        //**************************************************************
        if (cajaNombre.isEmpty() || cajaReferencia.isEmpty() || cajaTemperatura == 0 || cajaValorBase == 0) {
            JOptionPane.showMessageDialog(panelCuerpoProCrear, "Todos los valores son obligatorios.");
        } else {
            //******************************************************************
            //creacion de objetos
            //******************************************************************
            objDaoProducto = new DaoProducto();
            objProducto = new Producto();
            //******************************************************************
            objProducto.setNombre(cajaNombre);
            objProducto.setId(cajaReferencia);
            objProducto.setTemperatura(cajaTemperatura);
            objProducto.setValorBase(cajaValorBase);

            if (objDaoProducto.agregar(objProducto)) {
                JOptionPane.showMessageDialog(panelCuerpoProCrear, "EXITO: Registro agregado correctamente.");
            } else {
                JOptionPane.showMessageDialog(panelCuerpoProCrear, "ERROR: Registro NO FUE agregado correctamente.");
            }
            limpiarCajas();
        }
    }//GEN-LAST:event_btnCrearProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JLabel lblCrearProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblRefeProducto;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblValorBase;
    private javax.swing.JPanel panelBotonesProCrear;
    private javax.swing.JPanel panelCebeceraProCrear;
    private javax.swing.JPanel panelCuerpoProCrear;
    private javax.swing.JTextField txtCajaNombrePro;
    private javax.swing.JTextField txtCajaReferencia;
    private javax.swing.JTextField txtCajaTemperatura;
    private javax.swing.JTextField txtCajaValorBase;
    // End of variables declaration//GEN-END:variables
}
