package formularios;

import javax.swing.JInternalFrame;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuProductos = new javax.swing.JMenu();
        jMenuItemCrearPro = new javax.swing.JMenuItem();
        jMenuItemListarPro = new javax.swing.JMenuItem();
        jMenuItemAdminPro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crud Productos");
        setResizable(false);

        ventanaPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");
        jMenuArchivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItemAcercaDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemAcercaDe.setText("Acerca De");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAcercaDe);

        jMenuItemSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuProductos.setText("Productos");
        jMenuProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItemCrearPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemCrearPro.setText("Crear");
        jMenuItemCrearPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearProActionPerformed(evt);
            }
        });
        jMenuProductos.add(jMenuItemCrearPro);

        jMenuItemListarPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemListarPro.setText("Listar");
        jMenuItemListarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarProActionPerformed(evt);
            }
        });
        jMenuProductos.add(jMenuItemListarPro);

        jMenuItemAdminPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItemAdminPro.setText("Administrar");
        jMenuItemAdminPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdminProActionPerformed(evt);
            }
        });
        jMenuProductos.add(jMenuItemAdminPro);

        jMenuBar1.add(jMenuProductos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarVentanaPanel(JInternalFrame ventana){
        if (ventanaPrincipal.getComponentCount() > 0){
            ventanaPrincipal.removeAll();
        }
        ventanaPrincipal.add(ventana);
    }
    
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        //*************************************************
        //definicion de variables
        //*************************************************
        AcercaDe ventanaAcercaDe;
        //*************************************************
        //*************************************************
        //creacion de objetos
        //*************************************************
        ventanaAcercaDe = new AcercaDe();
        //*************************************************
        //*************************************************
        //agregar la ventana al panel
        //*************************************************
        agregarVentanaPanel(ventanaAcercaDe);
        //*************************************************
        //*************************************************
        //mostrar la ventana en el panel
        //*************************************************
        ventanaAcercaDe.show();
        //*************************************************
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemCrearProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearProActionPerformed
        //*************************************************
        //definicion de variables
        //*************************************************
        CrearProductos ventanaCrearProductos;
        //*************************************************
        //*************************************************
        //creacion de objetos
        //*************************************************
        ventanaCrearProductos = new CrearProductos();
        //*************************************************
        //*************************************************
        //agregar la ventana al panel
        //*************************************************
        agregarVentanaPanel(ventanaCrearProductos);
        //*************************************************
        //*************************************************
        //mostrar la ventana en el panel
        //*************************************************
        ventanaCrearProductos.show();
        //*************************************************
    }//GEN-LAST:event_jMenuItemCrearProActionPerformed

    private void jMenuItemListarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarProActionPerformed
        //*************************************************
        //definicion de variables
        //*************************************************
        ListarProductos ventanaListarProductos;
        //*************************************************
        //*************************************************
        //creacion de objetos
        //*************************************************
        ventanaListarProductos = new ListarProductos();
        //*************************************************
        //*************************************************
        //agregar la ventana al panel
        //*************************************************
        agregarVentanaPanel(ventanaListarProductos);
        //*************************************************
        //*************************************************
        //mostrar la ventana en el panel
        //*************************************************
        ventanaListarProductos.show();
        //*************************************************
    }//GEN-LAST:event_jMenuItemListarProActionPerformed

    private void jMenuItemAdminProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdminProActionPerformed
        //*************************************************
        //definicion de variables
        //*************************************************
        AdminProductos ventanaAdminProductos;
        //*************************************************
        //*************************************************
        //creacion de objetos
        //*************************************************
        ventanaAdminProductos = new AdminProductos();
        //*************************************************
        //*************************************************
        //agregar la ventana al panel
        //*************************************************
        agregarVentanaPanel(ventanaAdminProductos);
        //*************************************************
        //*************************************************
        //mostrar la ventana en el panel
        //*************************************************
        ventanaAdminProductos.show();
        //*************************************************
    }//GEN-LAST:event_jMenuItemAdminProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemAdminPro;
    private javax.swing.JMenuItem jMenuItemCrearPro;
    private javax.swing.JMenuItem jMenuItemListarPro;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuProductos;
    private javax.swing.JPanel ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
